<script setup lang="ts">
import { shallowRef } from 'vue'
const props = defineProps<{ setup: boolean; error: string | null; labels: Record<string, string> }>()
const emit = defineEmits<{ submit: [username: string, password: string]; toggleLocale: [] }>()
const username = shallowRef('admin'); const password = shallowRef('')
function submit() { emit('submit', username.value, password.value) }
</script>
<template><main class="auth-panel"><section class="auth-card"><button class="locale" type="button" @click="emit('toggleLocale')">{{ props.labels.language }}</button><p class="eyebrow">MediaGrap · private library</p><h1>{{ props.setup ? props.labels.setup : props.labels.welcome }}</h1><p>{{ props.setup ? 'This account controls media sources on this server.' : 'Sign in to review your library.' }}</p><form @submit.prevent="submit"><label>{{ props.labels.username }}<input v-model="username" autocomplete="username" minlength="3" required /></label><label>{{ props.labels.password }}<input v-model="password" type="password" :autocomplete="props.setup ? 'new-password' : 'current-password'" minlength="12" required /></label><p v-if="props.error" class="form-error">{{ props.error }}</p><button type="submit">{{ props.setup ? props.labels.create : props.labels.signIn }}</button></form></section></main></template>
<style scoped>.auth-panel{display:grid;min-height:100vh;place-items:center;padding:1.5rem;background:var(--ink-900)}.auth-card{position:relative;width:min(100%,31rem);padding:clamp(1.5rem,6vw,3.5rem);border:1px solid var(--water-700);border-radius:1rem;background:var(--paper)}h1{margin:.5rem 0;font:500 clamp(2.4rem,7vw,4rem)/.95 var(--font-display);letter-spacing:-.06em}.auth-card p{color:var(--ink-600);line-height:1.6}form{display:grid;gap:1rem;margin-top:1.8rem}label{display:grid;gap:.4rem;font-size:.85rem;font-weight:700}input{min-height:2.9rem;padding:.6rem .75rem;border:1px solid var(--mist-300);border-radius:.45rem}button{min-height:2.9rem;border:0;border-radius:.45rem;background:var(--ink-900);color:white;font-weight:700;cursor:pointer}.locale{position:absolute;top:1rem;right:1rem;min-height:2rem;padding:.25rem .5rem;background:var(--paper);color:var(--ink-900);border:1px solid var(--mist-300)}.form-error{margin:0;color:#9d3217}</style>
