ALTER TABLE jobs ADD COLUMN payload TEXT NOT NULL DEFAULT '{}';
ALTER TABLE jobs ADD COLUMN retry_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN max_retries INTEGER NOT NULL DEFAULT 2;
ALTER TABLE jobs ADD COLUMN next_run_at TEXT;
