import { computed, shallowRef } from 'vue'

export type Locale = 'en' | 'zh-CN'

const messages = {
  en: {
    opening: 'Opening MediaGrap…', setup: 'Create the first administrator', welcome: 'Welcome back', username: 'Username', password: 'Password', signIn: 'Sign in', create: 'Create administrator',
    authEyebrow: 'MediaGrap · private library', setupIntro: 'This account controls media sources on this server.', signInIntro: 'Sign in to review your library.',
    movies: 'Movies', tvShows: 'TV shows', sources: 'Sources', jobs: 'Jobs', settings: 'Settings', seasons: 'seasons', episodes: 'episodes', season: 'Season', language: '中文',
    operations: 'Operations', operationsEyebrow: 'Jobs · audit · runtime', operationsIntro: 'Monitor durable work, filesystem write history, and container health from real server data.', operationFailed: 'The operation failed.', jobQueue: 'Durable queue', jobCenter: 'Job center', jobHistory: 'History', cancelJob: 'Cancel', retryJob: 'Retry', jobWaiting: 'Waiting for a worker', noActiveJobs: 'No jobs are queued or running.', noJobHistory: 'No completed jobs yet.', stream_connecting: 'Connecting', stream_connected: 'Live', stream_reconnecting: 'Reconnecting', jobKind_scan: 'Library scan', jobKind_artwork_download: 'Artwork download', jobState_queued: 'Queued', jobState_running: 'Running', jobState_succeeded: 'Succeeded', jobState_failed: 'Failed', jobState_cancelled: 'Cancelled', jobState_interrupted: 'Interrupted', fileSafety: 'Filesystem safety', auditCenter: 'Audit & recovery', noAuditEntries: 'No write plans or results have been recorded.', noTarget: 'No file target', auditOutcome_previewed: 'Previewed', auditOutcome_applied: 'Applied', auditOutcome_recorded: 'Recorded', recoverability_atomic_replace_only: 'Atomic replacement only', recoverability_not_applicable: 'Not applicable', auditRecoveryNotice: 'Recovery is limited to the recorded operation and available backups; global rollback cannot be guaranteed after NAS or storage failure.', runtime: 'Container runtime', systemStatus: 'System status', applicationVersion: 'Application version', database: 'Database', cache: 'Cache', ready: 'Ready', unavailable: 'Unavailable', notConfigured: 'Not configured', mediaMounts: 'Media mounts', noMediaMounts: 'No configured media mounts.', providers: 'Providers', providerStatus_configured: 'Configured', providerStatus_not_configured: 'Not configured',
    serverConnected: 'Server connected', mainNavigation: 'Main navigation', switchLanguage: 'Switch language', admin: 'Admin', search: 'Search title, year, IMDb ID…', searchShows: 'Search TV shows…',
    refresh: 'Refresh', filterByStatus: 'Filter by status', movieList: 'Movie list', tvShowList: 'TV show list', unscraped: 'unscraped', nfoReady: 'NFO ready', nfoMissing: 'NFO missing', posterReady: 'Poster ready', posterMissing: 'Poster missing', fanartReady: 'Fanart ready', fanartMissing: 'Fanart missing',
    activeJob: 'Job', scanningTvLibrary: 'Scanning TV library', noFilms: 'No film files are indexed yet.', noShows: 'No TV episodes are indexed yet.', noMatch: 'Select a movie from the catalog to view details.', selectShow: 'Select a TV show to review its indexed episodes.', loading: 'Loading…', writable: 'Writable', readOnly: 'This source is read-only.',
    settingsIntro: 'Manage providers, network routing, scan schedules, and per-user preferences.', providerSettings: 'Metadata provider & network', directorySettings: 'Media directories', interfaceSettings: 'Interface', interfaceLanguage: 'Display language', interfaceTheme: 'Theme', themeDark: 'Dark', themeLight: 'Light', themeSystem: 'Follow system', savePreferences: 'Save preferences', interfaceEyebrow: 'Interface', providerEyebrow: 'Providers', libraryEyebrow: 'Library', settingsEyebrow: 'MediaGrap · control room', directoryHelp: 'Add one mounted parent directory, then choose its scan mode and optional restart-safe schedule.',
    tmdbApiKey: 'TMDb API key', fanartTvApiKey: 'Fanart.tv API key', fanartTvApiKeyPlaceholder: 'Paste a Fanart.tv project API key', fanartTvApiKeyHelp: 'Used for movie artwork groups; the key is kept server-side.', clearFanartTvApiKey: 'Disable the stored Fanart.tv API key', apiKeyConfigured: 'An API key is configured; enter a replacement to change it.', apiKeyPlaceholder: 'Paste a TMDb v3 API key', clearApiKey: 'Disable the stored TMDb API key', tmdbLanguage: 'Primary metadata language', fallbackLanguage: 'Fallback metadata language', fallbackLanguageHelp: 'Used when the preferred translation has missing fields.', outboundProxy: 'Outbound proxy', proxyConfigured: 'A proxy is configured; enter a replacement to change it.', proxyPlaceholder: 'http://proxy:7890 or socks5://proxy:1080', clearProxy: 'Disable the stored proxy', noProxyPlaceholder: 'localhost,.lan,192.168.1.10', noProxyHelp: 'Comma-separated hosts that bypass the configured proxy.', clearNoProxy: 'Clear stored NO_PROXY rules', configured: 'Configured', notSet: 'Not set', saveSettings: 'Save provider & network settings', saving: 'Saving…', testConnection: 'Test connection', testProxy: 'Test proxy', testingConnection: 'Testing…', connection_reachable: 'Reachable', connection_failed: 'Failed', connection_not_configured: 'Not configured', scanStrategy: 'Scan mode', incrementalScan: 'Incremental', fullScan: 'Full', scheduledScan: 'Scheduled', scanInterval: 'Interval (min)', savePolicy: 'Save policy',
    noSources: 'No media sources have been added.', openSettingsForSource: 'Open Settings to add an allowed mounted folder.', source: 'Media source', sourceType: 'Media type', selectSourceType: 'Select type (Movies / Shows)', sourceNamePlaceholder: 'Media library', containerPath: 'Container path', sourcePathPlaceholder: '/media/movies', addSource: 'Add media source', scan: 'Scan', deleteSource: 'Remove', confirmDeleteSource: 'Remove this media source and its MediaGrap index? Your media files will not be deleted.', sourceAdded: 'Media source added. Scan it to index movies and TV shows.', sourceDeleted: 'Media source and its index were removed. Media files were not changed.', errorAddSource: 'Unable to add media source.', errorSourceOutsideRoots: 'This path is outside the configured media-root allowlist.', errorSourceMissing: 'This path is not an accessible directory in the container.', errorSourceExists: 'This media source has already been added.', firstSource: 'Add your first media folder.', indexed: 'indexed files',
    overview: 'Overview', artworkTab: 'Artwork', castTab: 'Cast', nfoRaw: 'NFO raw', fileAudit: 'File audit', backToList: 'Back to list', saveAndWriteNfo: 'Save & write NFO', scrape: 'Scrape', searching: 'Searching…', lock: 'Lock', locked: 'Locked', lockMetadata: 'Lock metadata', metadataLocked: 'Metadata locked', runtimeMinutes: 'min', posterAlt: 'Movie poster', noPosterLoaded: 'No poster loaded', fanart: 'Fanart', logo: 'Logo', fanartUnavailable: 'Fanart unavailable',
    plotSummary: 'Plot summary', saveDraft: 'Save draft', enterPlot: 'Enter movie plot summary…', releaseDate: 'Release date', yearPlaceholder: 'YYYY', director: 'Director', directorPlaceholder: 'Director', writer: 'Writer', writers: 'Writers', writerPlaceholder: 'Writer, Screenplay', studio: 'Studio', studioPlaceholder: 'Production company', genres: 'Genres', genresPlaceholder: 'Animation, Action, Music', fileHealthy: 'Healthy', fileSize: 'File size', videoSummaryPlaceholder: 'Technical media details are not available yet.',
    artworkGallery: 'Artwork & fanart gallery', localArtwork: 'Local artwork', uploadCustomImage: 'Upload custom image', scrapeFanart: 'Scrape Fanart.tv', clearLogo: 'Clear logo', clearArt: 'Clear art', discArt: 'Disc art', landscape: 'Landscape', banner: 'Banner', bannerPreview: 'MediaGrap banner preview', castAndCrew: 'Cast & crew', scrapeHeadshots: 'Scrape actor headshots', avatarAlt: 'Avatar', nfoXmlEditor: 'NFO XML metadata editor', saveToNfo: 'Save to NFO file', filesRenamePlanner: 'Files & safe rename planner', runDryRun: 'Run dry-run simulation', video: 'Video', matched: 'Matched', validKodi: 'Valid Kodi NFO', fileResolutionUnavailable: 'Resolution unavailable',
    fileAuditReadOnly: 'Real filesystem state and preview-only naming; no files will be changed.', previewOnly: 'PREVIEW ONLY', currentFiles: 'Current file & sidecar audit', files: 'files', type: 'Type', path: 'Relative path', size: 'Size', mimeType: 'MIME type', modifiedAt: 'Modified', permissions: 'Permissions', status: 'Status', valid: 'Valid', inspectingMedia: 'Inspecting media…', fileAuditUnavailable: 'File audit is unavailable.', mediaInfoUnavailable: 'ffprobe media information is unavailable.', mediaStreams: 'Embedded media streams', cachedProbe: 'CACHED', videoStreams: 'Video', audioStreams: 'Audio', subtitleStreams: 'Subtitles', subtitleTracks: 'subtitle tracks', noEmbeddedSubtitles: 'No embedded subtitle streams.', languageUnknown: 'Language unknown', namingPattern: 'Naming pattern dry-run', patternTemplate: 'FILENAME PATTERN', availableTokens: 'Available naming tokens', previewing: 'Previewing…', namingConflictsFound: 'Conflicts found. This preview cannot be applied.', namingPreviewSafe: 'Preview complete. No files were changed.', fileNeedsAttention: 'Needs attention', audit_symlink: 'Symlink — not followed', audit_read_only: 'Read-only', audit_not_regular: 'Not a regular file', audit_invalid_xml: 'Invalid XML', audit_invalid_mime: 'Content does not match image type', audit_unreadable: 'Unreadable', audit_missing: 'Missing',
    tvShowDetails: 'TV show details', episodesAndSeasons: 'Episodes & seasons', batchScrapeAll: 'Batch scrape all', scrapeTvShow: 'Match TV show', previewTvNfo: 'Preview TV NFO writes', matchTvShow: 'Match TV show', matchTvHint: 'Selecting a TMDb candidate immediately replaces TV metadata and atomically writes the show, season, and episode NFO files. Local images are never changed.', metadataReady: 'TMDb metadata', metadataFromNfo: 'Local NFO', metadataEmpty: 'Not matched', noLocalArtwork: 'No local artwork was found for this show.', noCastLoaded: 'No cast metadata is available.', tvSeries: 'TV series', ratingUnavailable: 'Rating unavailable', episodesCount: 'episodes', scrapedStatusUnavailable: 'Scrape status unavailable', code: 'Code', titleAndPath: 'Title / relative path', quality: 'Quality', nfo: 'NFO', qualityUnavailable: 'Quality unavailable', nfoStatusUnavailable: 'NFO status unavailable',
    tmdbSearch: 'TMDb search', tmdbMatch: 'TMDb match', matchCandidates: 'Match candidates', results: 'results', closeCandidates: 'Close candidates', searchingCandidates: 'Searching TMDb for matching candidates…', select: 'Select', noCandidates: 'No matching candidates found.', nfoSavePreview: 'NFO save preview', conflict: 'Conflict', overwrite: 'Overwrite', newFile: 'New file', nfoPreview: 'NFO preview', closeNfoPreview: 'Close NFO preview', target: 'Target', nfoConflictHelp: 'The target is not a regular NFO file and cannot be replaced.', nfoReplaceHelp: 'An existing local NFO will be replaced atomically.', xmlContent: 'XML content', cancel: 'Cancel', apply: 'Apply',
    artworkPreview: 'Artwork download preview', closeArtworkPreview: 'Close artwork download preview', artworkHelp: 'Fanart.tv candidates are downloaded beside the movie only after confirmation.', poster: 'Poster', artworkCreate: 'A new local image will be created.', artworkReplace: 'An existing local image will be atomically replaced.', artworkConflict: 'This target is not a regular image file.', downloadArtwork: 'Download artwork', downloading: 'Downloading…', artworkEyebrow: 'Fanart.tv artwork', artworkCandidates: 'Fanart.tv candidates', artworkDialogHelp: 'Choose one image per artwork type, then preview the download plan.', artworkSelectionHint: 'Your files are not changed until download is confirmed.', artworkProxyHint: 'Images are requested through the server proxy.', closeArtworkCandidates: 'Close artwork candidates', artworkExisting: 'Already on disk', artworkGroups: 'groups', artworkRefresh: 'Refresh candidates', artworkSelect: 'Select', artworkSelected: 'Selected', artworkNoCandidates: 'No Fanart.tv artwork found.', artworkQueued: 'Artwork download queued', artworkDimensions: 'Dimensions', artworkLanguage: 'Language',
    errorSignIn: 'Unable to sign in', errorLoadMedia: 'Unable to load media details', errorSearchCandidates: 'Failed to search candidates', errorApplyCandidate: 'Failed to apply candidate', errorSaveMetadata: 'Failed to save metadata', errorPreviewNfo: 'Failed to preview NFO', errorWriteNfo: 'Failed to write NFO', errorLoadShow: 'Unable to load TV show details',
    executeRename: 'Execute Safe Rename & Move', dryRunSimulation: 'Dry Run Simulation', noConflictsDetected: 'No conflicts detected', conflictsDetected: 'Conflicts detected — cannot execute', renameQueued: 'Rename job queued. Track progress in the Jobs panel.', renameDir: 'RENAME DIR', renameFile: 'RENAME FILE', presetKodi: 'Kodi Standard', presetPlex: 'Plex Standard', presetCustom: 'Custom', patternPreset: 'Preset',
    collapsePreview: 'Collapse preview', expandPreview: 'Expand preview', closePreview: 'Close preview',
    renameScope: 'Rename scope', scopeAllEpisodes: 'Whole show (All episodes)', scopeSeason: 'Season', scopeSingleEpisode: 'Selected episode', presetKodiTV: 'Kodi Standard', presetKodiTVWithTitle: 'Kodi (with Title)', presetPlexTV: 'Plex Standard', presetJellyfinTV: 'Jellyfin / Emby', presetFlatTV: 'Flat (No Season folder)',
  },
  'zh-CN': {
    opening: '正在打开 MediaGrap…', setup: '创建首个管理员', welcome: '欢迎回来', username: '用户名', password: '密码', signIn: '登录', create: '创建管理员',
    authEyebrow: 'MediaGrap · 私有媒体库', setupIntro: '此账户可以管理本服务器上的媒体源。', signInIntro: '登录后查看和管理媒体库。',
    movies: '电影', tvShows: '剧集', sources: '数据源', jobs: '任务', settings: '设置', seasons: '季', episodes: '集', season: '第', language: 'EN',
    operations: '作业与运维', operationsEyebrow: '作业 · 审计 · 运行状态', operationsIntro: '使用服务端真实数据查看持久化作业、文件写入历史和容器健康状态。', operationFailed: '操作失败。', jobQueue: '持久化队列', jobCenter: '作业中心', jobHistory: '历史记录', cancelJob: '取消', retryJob: '重试', jobWaiting: '等待工作线程', noActiveJobs: '当前没有排队或运行中的作业。', noJobHistory: '暂无已结束作业。', stream_connecting: '正在连接', stream_connected: '实时', stream_reconnecting: '正在重连', jobKind_scan: '媒体库扫描', jobKind_artwork_download: '图片下载', jobState_queued: '排队中', jobState_running: '运行中', jobState_succeeded: '已完成', jobState_failed: '失败', jobState_cancelled: '已取消', jobState_interrupted: '已中断', fileSafety: '文件安全', auditCenter: '审计与恢复', noAuditEntries: '尚未记录写入计划或结果。', noTarget: '无文件目标', auditOutcome_previewed: '已预览', auditOutcome_applied: '已执行', auditOutcome_recorded: '已记录', recoverability_atomic_replace_only: '仅限原子替换范围', recoverability_not_applicable: '不适用', auditRecoveryNotice: '恢复范围取决于已记录操作和实际存在的备份；NAS 或存储故障后不承诺全局回滚。', runtime: '容器运行环境', systemStatus: '系统状态', applicationVersion: '应用版本', database: '数据库', cache: '缓存', ready: '就绪', unavailable: '不可用', notConfigured: '未配置', mediaMounts: '媒体挂载', noMediaMounts: '尚未配置媒体挂载。', providers: '提供方', providerStatus_configured: '已配置', providerStatus_not_configured: '未配置',
    serverConnected: '服务器已连接', mainNavigation: '主导航', switchLanguage: '切换语言', admin: '管理员', search: '搜索片名、年份、IMDb ID…', searchShows: '搜索剧集…',
    refresh: '刷新', filterByStatus: '按状态筛选', movieList: '电影列表', tvShowList: '剧集列表', unscraped: '未刮削', nfoReady: 'NFO 就绪', nfoMissing: '缺少 NFO', posterReady: '海报就绪', posterMissing: '缺少海报', fanartReady: '背景图就绪', fanartMissing: '缺少背景图',
    activeJob: '任务', scanningTvLibrary: '正在扫描剧集库', noFilms: '尚未索引电影文件。', noShows: '尚未索引剧集文件。', noMatch: '从目录中选择一部电影以查看详情。', selectShow: '选择一个剧集以查看已索引的季和集。', loading: '正在加载…', writable: '可写', readOnly: '此媒体源为只读，无法写入。',
    settingsIntro: '管理元数据提供方、网络路由、扫描计划和当前用户偏好。', providerSettings: '元数据提供方与网络', directorySettings: '媒体目录', interfaceSettings: '界面', interfaceLanguage: '显示语言', interfaceTheme: '主题', themeDark: '深色', themeLight: '浅色', themeSystem: '跟随系统', savePreferences: '保存界面偏好', interfaceEyebrow: '界面', providerEyebrow: '提供方', libraryEyebrow: '媒体库', settingsEyebrow: 'MediaGrap · 控制台', directoryHelp: '添加已挂载的父目录，并配置扫描模式和可选的持久化定时任务。',
    tmdbApiKey: 'TMDb API Key', fanartTvApiKey: 'Fanart.tv API Key', fanartTvApiKeyPlaceholder: '粘贴 Fanart.tv 项目 API Key', fanartTvApiKeyHelp: '用于读取电影图片分组；Key 只保存在服务端。', clearFanartTvApiKey: '停用已保存的 Fanart.tv API Key', apiKeyConfigured: '已配置 API Key；输入新值可替换。', apiKeyPlaceholder: '粘贴 TMDb v3 API Key', clearApiKey: '停用已保存的 TMDb API Key', tmdbLanguage: '首选元数据语言', fallbackLanguage: '元数据回退语言', fallbackLanguageHelp: '首选翻译缺少字段时使用。', outboundProxy: '出站代理', proxyConfigured: '已配置代理；输入新值可替换。', proxyPlaceholder: 'http://proxy:7890 或 socks5://proxy:1080', clearProxy: '停用已保存的代理', noProxyPlaceholder: 'localhost,.lan,192.168.1.10', noProxyHelp: '使用逗号分隔不经过代理的主机。', clearNoProxy: '清除已保存的 NO_PROXY 规则', configured: '已配置', notSet: '未设置', saveSettings: '保存提供方与网络设置', saving: '正在保存…', testConnection: '连接测试', testProxy: '代理测速', testingConnection: '测试中…', connection_reachable: '连接正常', connection_failed: '连接失败', connection_not_configured: '未配置', scanStrategy: '扫描模式', incrementalScan: '增量扫描', fullScan: '全量扫描', scheduledScan: '定时扫描', scanInterval: '间隔（分钟）', savePolicy: '保存策略',
    noSources: '尚未添加媒体源。', openSettingsForSource: '请前往“设置”添加已允许的挂载目录。', source: '媒体源', sourceType: '媒体类型', selectSourceType: '选择类型（电影 Movies / 剧集 Shows）', sourceNamePlaceholder: '媒体库', containerPath: '容器路径', sourcePathPlaceholder: '/media/movies', addSource: '添加媒体源', scan: '扫描', deleteSource: '删除', confirmDeleteSource: '删除此媒体源及其 MediaGrap 索引吗？不会删除任何媒体文件。', sourceAdded: '媒体源已添加。扫描后会索引电影和电视剧。', sourceDeleted: '媒体源及其索引已删除；媒体文件未被修改。', errorAddSource: '无法添加媒体源。', errorSourceOutsideRoots: '该路径不在配置的媒体根目录允许范围内。', errorSourceMissing: '该路径不是容器中可访问的目录。', errorSourceExists: '该媒体源已添加。', firstSource: '添加第一个媒体目录。', indexed: '已索引文件',
    overview: '概览', artworkTab: '图片资源', castTab: '演职人员', nfoRaw: 'NFO 原文', fileAudit: '文件审计', backToList: '返回列表', saveAndWriteNfo: '保存并写入 NFO', scrape: '刮削', searching: '正在搜索…', lock: '锁定', locked: '已锁定', lockMetadata: '锁定元数据', metadataLocked: '元数据已锁定', runtimeMinutes: '分钟', posterAlt: '电影海报', noPosterLoaded: '未加载海报', fanart: '背景图', logo: '标志', fanartUnavailable: '暂无背景图',
    plotSummary: '剧情简介', saveDraft: '保存草稿', enterPlot: '输入电影剧情简介…', releaseDate: '上映日期', yearPlaceholder: '年份', director: '导演', directorPlaceholder: '导演', writer: '编剧', writers: '编剧', writerPlaceholder: '编剧、剧本', studio: '制作公司', studioPlaceholder: '制作公司', genres: '类型', genresPlaceholder: '动画、动作、音乐', fileHealthy: '正常', fileSize: '文件大小', videoSummaryPlaceholder: '尚未提供媒体技术信息。',
    artworkGallery: '图片资源与背景图图库', localArtwork: '本地图片', uploadCustomImage: '上传自定义图片', scrapeFanart: '从 Fanart.tv 刮削', clearLogo: '透明标志', clearArt: '透明艺术图', discArt: '光盘图', landscape: '横向图片', banner: '横幅', bannerPreview: 'MediaGrap 横幅预览', castAndCrew: '演职人员', scrapeHeadshots: '刮削演员头像', avatarAlt: '头像', nfoXmlEditor: 'NFO XML 元数据编辑器', saveToNfo: '保存到 NFO 文件', filesRenamePlanner: '文件与安全重命名计划', runDryRun: '执行模拟预览', video: '视频', matched: '已匹配', validKodi: '有效的 Kodi NFO', fileResolutionUnavailable: '分辨率未知',
    fileAuditReadOnly: '展示真实文件状态与只读命名预览；不会修改任何文件。', previewOnly: '仅预览', currentFiles: '当前文件与 Sidecar 审计', files: '个文件', type: '类型', path: '相对路径', size: '大小', mimeType: 'MIME 类型', modifiedAt: '修改时间', permissions: '权限', status: '状态', valid: '有效', inspectingMedia: '正在探测媒体…', fileAuditUnavailable: '无法读取文件审计信息。', mediaInfoUnavailable: 'ffprobe 媒体信息不可用。', mediaStreams: '内嵌媒体流', cachedProbe: '已缓存', videoStreams: '视频流', audioStreams: '音频流', subtitleStreams: '字幕流', subtitleTracks: '条字幕轨', noEmbeddedSubtitles: '未发现内嵌字幕轨。', languageUnknown: '语言未知', namingPattern: '命名规则 Dry-Run', patternTemplate: '文件名模板', availableTokens: '可用命名变量', previewing: '正在计算…', namingConflictsFound: '发现命名冲突；此预览不可执行。', namingPreviewSafe: '预览完成；未修改任何文件。', fileNeedsAttention: '需要注意', audit_symlink: '软链接（未跟随）', audit_read_only: '只读', audit_not_regular: '不是普通文件', audit_invalid_xml: 'XML 无效', audit_invalid_mime: '内容与图片类型不匹配', audit_unreadable: '无法读取', audit_missing: '文件缺失',
    tvShowDetails: '剧集详情', episodesAndSeasons: '剧集与季', batchScrapeAll: '批量刮削全部', scrapeTvShow: '匹配剧集', previewTvNfo: '预览剧集 NFO 写入', matchTvShow: '匹配剧集', matchTvHint: '选中 TMDb 候选会立即替换剧集元数据，并原子写入剧、季和单集 NFO；本地图片不会被修改。', metadataReady: 'TMDb 元数据', metadataFromNfo: '本地 NFO', metadataEmpty: '尚未匹配', noLocalArtwork: '此剧集未发现本地图片。', noCastLoaded: '暂无演职员元数据。', tvSeries: '剧集', ratingUnavailable: '评分未知', episodesCount: '集', scrapedStatusUnavailable: '刮削状态未知', code: '编号', titleAndPath: '标题 / 相对路径', quality: '清晰度未知', nfo: 'NFO', qualityUnavailable: '清晰度未知', nfoStatusUnavailable: 'NFO 状态未知',
    tmdbSearch: 'TMDb 搜索', tmdbMatch: 'TMDb 匹配', matchCandidates: '候选结果', results: '个结果', closeCandidates: '关闭候选结果', searchingCandidates: '正在从 TMDb 搜索候选结果…', select: '选择', noCandidates: '未找到匹配的候选结果。', nfoSavePreview: 'NFO 保存预览', conflict: '冲突', overwrite: '覆盖', newFile: '新文件', nfoPreview: 'NFO 预览', closeNfoPreview: '关闭 NFO 预览', target: '目标', nfoConflictHelp: '目标不是可替换的普通 NFO 文件。', nfoReplaceHelp: '已有本地 NFO 将以原子方式替换。', xmlContent: 'XML 内容', cancel: '取消', apply: '应用',
    artworkPreview: '图片下载预览', closeArtworkPreview: '关闭图片下载预览', artworkHelp: '仅下载已选择的 Fanart.tv 图片；确认后才会写入电影所在目录。', poster: '海报', artworkCreate: '将创建新的本地图片文件。', artworkReplace: '将以原子方式替换已有本地图片。', artworkConflict: '目标不是可替换的普通图片文件。', downloadArtwork: '下载图片', downloading: '正在下载…', artworkEyebrow: 'Fanart.tv 图片资源', artworkCandidates: 'Fanart.tv 候选图片', artworkDialogHelp: '为每种图片类型选择一张，然后预览下载计划。', artworkSelectionHint: '确认下载前不会修改本地文件。', artworkProxyHint: '图片请求会通过服务端代理。', closeArtworkCandidates: '关闭图片候选', artworkExisting: '本地已有', artworkGroups: '组', artworkRefresh: '刷新候选', artworkSelect: '选择', artworkSelected: '已选择', artworkNoCandidates: 'Fanart.tv 没有找到图片。', artworkQueued: '图片下载任务已排队', artworkDimensions: '尺寸', artworkLanguage: '语言',
    errorSignIn: '无法登录', errorLoadMedia: '无法加载媒体详情', errorSearchCandidates: '搜索候选结果失败', errorApplyCandidate: '应用候选结果失败', errorSaveMetadata: '保存元数据失败', errorPreviewNfo: '预览 NFO 失败', errorWriteNfo: '写入 NFO 失败', errorLoadShow: '无法加载电视剧详情',
    executeRename: '执行安全重命名与移动', dryRunSimulation: '模拟预览', noConflictsDetected: '未发现冲突', conflictsDetected: '存在冲突 — 无法执行', renameQueued: '重命名任务已加入队列，请在作业面板追踪进度。', renameDir: '重命名目录', renameFile: '重命名文件', presetKodi: 'Kodi 标准', presetPlex: 'Plex 标准', presetCustom: '自定义', patternPreset: '预设',
    collapsePreview: '收起预览', expandPreview: '展开预览', closePreview: '关闭预览',
    renameScope: '重命名范围', scopeAllEpisodes: '整部剧集（全部集）', scopeSeason: '第', scopeSingleEpisode: '选中单集', presetKodiTV: 'Kodi 标准', presetKodiTVWithTitle: 'Kodi 标准（带单集标题）', presetPlexTV: 'Plex 标准', presetJellyfinTV: 'Jellyfin / Emby', presetFlatTV: '平铺（无 Season 目录）',
  }
} as const

export function useLocale() {
  const initial = localStorage.getItem('mediagrap.locale') === 'zh-CN' ? 'zh-CN' : 'en'
  const locale = shallowRef<Locale>(initial)
  const t = computed(() => messages[locale.value])

  function setLocale(value: Locale) {
    locale.value = value
    localStorage.setItem('mediagrap.locale', value)
  }

  function toggleLocale() {
    setLocale(locale.value === 'en' ? 'zh-CN' : 'en')
  }

  return { locale, t, setLocale, toggleLocale }
}
