import { computed, shallowRef } from 'vue'

export type Locale = 'en' | 'zh-CN'

const messages = {
  en: {
    opening: 'Opening MediaGrap…', setup: 'Create the first administrator', welcome: 'Welcome back', username: 'Username', password: 'Password', signIn: 'Sign in', create: 'Create administrator',
    authEyebrow: 'MediaGrap · private library', setupIntro: 'This account controls media sources on this server.', signInIntro: 'Sign in to review your library.',
    movies: 'Movies', tvShows: 'TV shows', sources: 'Sources', jobs: 'Jobs', settings: 'Settings', seasons: 'seasons', episodes: 'episodes', season: 'Season', language: '中文',
    serverConnected: 'Server connected', mainNavigation: 'Main navigation', switchLanguage: 'Switch language', admin: 'Admin', search: 'Search title, year, IMDb ID…', searchShows: 'Search TV shows…',
    refresh: 'Refresh', filterByStatus: 'Filter by status', movieList: 'Movie list', tvShowList: 'TV show list', unscraped: 'unscraped', nfoReady: 'NFO ready', nfoMissing: 'NFO missing', posterReady: 'Poster ready', posterMissing: 'Poster missing', fanartReady: 'Fanart ready', fanartMissing: 'Fanart missing',
    activeJob: 'Job', scanningTvLibrary: 'Scanning TV library', noFilms: 'No film files are indexed yet.', noShows: 'No TV episodes are indexed yet.', noMatch: 'Select a movie from the catalog to view details.', selectShow: 'Select a TV show to review its indexed episodes.', loading: 'Loading…', writable: 'Writable', readOnly: 'This source is read-only.',
    settingsIntro: 'Provider credentials and mounted media sources are managed here.', providerSettings: 'Metadata provider', directorySettings: 'Media directories', interfaceSettings: 'Interface', interfaceLanguage: 'Display language', interfaceEyebrow: 'Interface', providerEyebrow: 'TMDb', libraryEyebrow: 'Library', settingsEyebrow: 'MediaGrap · control room', directoryHelp: 'Add one mounted parent directory (for example, /media). Movies and TV shows beneath it are detected automatically.',
    tmdbApiKey: 'TMDb API key', apiKeyConfigured: 'An API key is configured; enter a replacement to change it.', apiKeyPlaceholder: 'Paste a TMDb v3 API key', clearApiKey: 'Disable the stored TMDb API key', tmdbLanguage: 'TMDb result language', outboundProxy: 'Outbound proxy', proxyConfigured: 'A proxy is configured; enter a replacement to change it.', proxyPlaceholder: 'http://proxy:7890', clearProxy: 'Disable the stored proxy', configured: 'Configured', notSet: 'Not set', saveSettings: 'Save provider settings', saving: 'Saving…',
    noSources: 'No media sources have been added.', openSettingsForSource: 'Open Settings to add an allowed mounted folder.', source: 'Media source', sourceNamePlaceholder: 'Media library', containerPath: 'Container path', sourcePathPlaceholder: '/media', addSource: 'Add media source', scan: 'Scan', deleteSource: 'Remove', confirmDeleteSource: 'Remove this media source and its MediaGrap index? Your media files will not be deleted.', sourceAdded: 'Media source added. Scan it to index movies and TV shows.', sourceDeleted: 'Media source and its index were removed. Media files were not changed.', errorAddSource: 'Unable to add media source.', errorSourceOutsideRoots: 'This path is outside the configured media-root allowlist.', errorSourceMissing: 'This path is not an accessible directory in the container.', errorSourceExists: 'This media source has already been added.', firstSource: 'Add your first media folder.', indexed: 'indexed files',
    overview: 'Overview', artworkTab: 'Artwork', castTab: 'Cast', nfoRaw: 'NFO raw', fileAudit: 'File audit', backToList: 'Back to list', saveAndWriteNfo: 'Save & write NFO', scrape: 'Scrape', searching: 'Searching…', lock: 'Lock', locked: 'Locked', lockMetadata: 'Lock metadata', metadataLocked: 'Metadata locked', runtimeMinutes: 'min', posterAlt: 'Movie poster', noPosterLoaded: 'No poster loaded', fanart: 'Fanart', logo: 'Logo', fanartUnavailable: 'Fanart unavailable',
    plotSummary: 'Plot summary', saveDraft: 'Save draft', enterPlot: 'Enter movie plot summary…', releaseDate: 'Release date', yearPlaceholder: 'YYYY', director: 'Director', directorPlaceholder: 'Director', writer: 'Writer', writers: 'Writers', writerPlaceholder: 'Writer, Screenplay', studio: 'Studio', studioPlaceholder: 'Production company', genres: 'Genres', genresPlaceholder: 'Animation, Action, Music', fileHealthy: 'Healthy', fileSize: 'File size', videoSummaryPlaceholder: 'Technical media details are not available yet.',
    artworkGallery: 'Artwork & fanart gallery', localArtwork: 'Local artwork', uploadCustomImage: 'Upload custom image', scrapeFanart: 'Scrape Fanart.tv', clearLogo: 'Clear logo', banner: 'Banner', bannerPreview: 'MediaGrap banner preview', castAndCrew: 'Cast & crew', scrapeHeadshots: 'Scrape actor headshots', avatarAlt: 'Avatar', nfoXmlEditor: 'NFO XML metadata editor', saveToNfo: 'Save to NFO file', filesRenamePlanner: 'Files & safe rename planner', runDryRun: 'Run dry-run simulation', video: 'Video', matched: 'Matched', validKodi: 'Valid Kodi NFO', fileResolutionUnavailable: 'Resolution unavailable',
    tvShowDetails: 'TV show details', episodesAndSeasons: 'Episodes & seasons', batchScrapeAll: 'Batch scrape all', scrapeTvShow: 'Match TV show', previewTvNfo: 'Preview TV NFO writes', matchTvShow: 'Match TV show', matchTvHint: 'Selecting a TMDb candidate immediately replaces TV metadata and atomically writes the show, season, and episode NFO files. Local images are never changed.', metadataReady: 'TMDb metadata', metadataFromNfo: 'Local NFO', metadataEmpty: 'Not matched', noLocalArtwork: 'No local artwork was found for this show.', noCastLoaded: 'No cast metadata is available.', tvSeries: 'TV series', ratingUnavailable: 'Rating unavailable', episodesCount: 'episodes', scrapedStatusUnavailable: 'Scrape status unavailable', code: 'Code', titleAndPath: 'Title / relative path', quality: 'Quality', nfo: 'NFO', qualityUnavailable: 'Quality unavailable', nfoStatusUnavailable: 'NFO status unavailable',
    tmdbSearch: 'TMDb search', tmdbMatch: 'TMDb match', matchCandidates: 'Match candidates', results: 'results', closeCandidates: 'Close candidates', searchingCandidates: 'Searching TMDb for matching candidates…', select: 'Select', noCandidates: 'No matching candidates found.', nfoSavePreview: 'NFO save preview', conflict: 'Conflict', overwrite: 'Overwrite', newFile: 'New file', nfoPreview: 'NFO preview', closeNfoPreview: 'Close NFO preview', target: 'Target', nfoConflictHelp: 'The target is not a regular NFO file and cannot be replaced.', nfoReplaceHelp: 'An existing local NFO will be replaced atomically.', xmlContent: 'XML content', cancel: 'Cancel', apply: 'Apply',
    artworkPreview: 'Artwork download preview', artworkHelp: 'Downloads use the selected TMDb JPEG files and write beside the movie only after confirmation.', poster: 'Poster', artworkCreate: 'A new local image will be created.', artworkReplace: 'An existing local image will be atomically replaced.', artworkConflict: 'This target is not a regular image file.', downloadArtwork: 'Download artwork', downloading: 'Downloading…', artworkEyebrow: 'TMDb artwork',
    errorSignIn: 'Unable to sign in', errorLoadMedia: 'Unable to load media details', errorSearchCandidates: 'Failed to search candidates', errorApplyCandidate: 'Failed to apply candidate', errorSaveMetadata: 'Failed to save metadata', errorPreviewNfo: 'Failed to preview NFO', errorWriteNfo: 'Failed to write NFO', errorLoadShow: 'Unable to load TV show details'
  },
  'zh-CN': {
    opening: '正在打开 MediaGrap…', setup: '创建首个管理员', welcome: '欢迎回来', username: '用户名', password: '密码', signIn: '登录', create: '创建管理员',
    authEyebrow: 'MediaGrap · 私有媒体库', setupIntro: '此账户可以管理本服务器上的媒体源。', signInIntro: '登录后查看和管理媒体库。',
    movies: '电影', tvShows: '剧集', sources: '数据源', jobs: '任务', settings: '设置', seasons: '季', episodes: '集', season: '第', language: 'EN',
    serverConnected: '服务器已连接', mainNavigation: '主导航', switchLanguage: '切换语言', admin: '管理员', search: '搜索片名、年份、IMDb ID…', searchShows: '搜索剧集…',
    refresh: '刷新', filterByStatus: '按状态筛选', movieList: '电影列表', tvShowList: '剧集列表', unscraped: '未刮削', nfoReady: 'NFO 就绪', nfoMissing: '缺少 NFO', posterReady: '海报就绪', posterMissing: '缺少海报', fanartReady: '背景图就绪', fanartMissing: '缺少背景图',
    activeJob: '任务', scanningTvLibrary: '正在扫描剧集库', noFilms: '尚未索引电影文件。', noShows: '尚未索引剧集文件。', noMatch: '从目录中选择一部电影以查看详情。', selectShow: '选择一个剧集以查看已索引的季和集。', loading: '正在加载…', writable: '可写', readOnly: '此媒体源为只读，无法写入。',
    settingsIntro: '在这里管理刮削器凭据和已挂载的媒体源。', providerSettings: '元数据提供方', directorySettings: '媒体目录', interfaceSettings: '界面', interfaceLanguage: '显示语言', interfaceEyebrow: '界面', providerEyebrow: 'TMDb', libraryEyebrow: '媒体库', settingsEyebrow: 'MediaGrap · 控制台', directoryHelp: '添加一个已挂载的父目录（例如 /media）；其下电影和电视剧会自动识别。',
    tmdbApiKey: 'TMDb API Key', apiKeyConfigured: '已配置 API Key；输入新值可替换。', apiKeyPlaceholder: '粘贴 TMDb v3 API Key', clearApiKey: '停用已保存的 TMDb API Key', tmdbLanguage: 'TMDb 搜索信息语言', outboundProxy: '出站代理', proxyConfigured: '已配置代理；输入新值可替换。', proxyPlaceholder: 'http://proxy:7890', clearProxy: '停用已保存的代理', configured: '已配置', notSet: '未设置', saveSettings: '保存提供方设置', saving: '正在保存…',
    noSources: '尚未添加媒体源。', openSettingsForSource: '请前往“设置”添加已允许的挂载目录。', source: '媒体源', sourceNamePlaceholder: '媒体库', containerPath: '容器路径', sourcePathPlaceholder: '/media', addSource: '添加媒体源', scan: '扫描', deleteSource: '删除', confirmDeleteSource: '删除此媒体源及其 MediaGrap 索引吗？不会删除任何媒体文件。', sourceAdded: '媒体源已添加。扫描后会索引电影和电视剧。', sourceDeleted: '媒体源及其索引已删除；媒体文件未被修改。', errorAddSource: '无法添加媒体源。', errorSourceOutsideRoots: '该路径不在配置的媒体根目录允许范围内。', errorSourceMissing: '该路径不是容器中可访问的目录。', errorSourceExists: '该媒体源已添加。', firstSource: '添加第一个媒体目录。', indexed: '已索引文件',
    overview: '概览', artworkTab: '图片资源', castTab: '演职人员', nfoRaw: 'NFO 原文', fileAudit: '文件审计', backToList: '返回列表', saveAndWriteNfo: '保存并写入 NFO', scrape: '刮削', searching: '正在搜索…', lock: '锁定', locked: '已锁定', lockMetadata: '锁定元数据', metadataLocked: '元数据已锁定', runtimeMinutes: '分钟', posterAlt: '电影海报', noPosterLoaded: '未加载海报', fanart: '背景图', logo: '标志', fanartUnavailable: '暂无背景图',
    plotSummary: '剧情简介', saveDraft: '保存草稿', enterPlot: '输入电影剧情简介…', releaseDate: '上映日期', yearPlaceholder: '年份', director: '导演', directorPlaceholder: '导演', writer: '编剧', writers: '编剧', writerPlaceholder: '编剧、剧本', studio: '制作公司', studioPlaceholder: '制作公司', genres: '类型', genresPlaceholder: '动画、动作、音乐', fileHealthy: '正常', fileSize: '文件大小', videoSummaryPlaceholder: '尚未提供媒体技术信息。',
    artworkGallery: '图片资源与背景图图库', localArtwork: '本地图片', uploadCustomImage: '上传自定义图片', scrapeFanart: '从 Fanart.tv 刮削', clearLogo: '透明标志', banner: '横幅', bannerPreview: 'MediaGrap 横幅预览', castAndCrew: '演职人员', scrapeHeadshots: '刮削演员头像', avatarAlt: '头像', nfoXmlEditor: 'NFO XML 元数据编辑器', saveToNfo: '保存到 NFO 文件', filesRenamePlanner: '文件与安全重命名计划', runDryRun: '执行模拟预览', video: '视频', matched: '已匹配', validKodi: '有效的 Kodi NFO', fileResolutionUnavailable: '分辨率未知',
    tvShowDetails: '剧集详情', episodesAndSeasons: '剧集与季', batchScrapeAll: '批量刮削全部', scrapeTvShow: '匹配剧集', previewTvNfo: '预览剧集 NFO 写入', matchTvShow: '匹配剧集', matchTvHint: '选中 TMDb 候选会立即替换剧集元数据，并原子写入剧、季和单集 NFO；本地图片不会被修改。', metadataReady: 'TMDb 元数据', metadataFromNfo: '本地 NFO', metadataEmpty: '尚未匹配', noLocalArtwork: '此剧集未发现本地图片。', noCastLoaded: '暂无演职员元数据。', tvSeries: '剧集', ratingUnavailable: '评分未知', episodesCount: '集', scrapedStatusUnavailable: '刮削状态未知', code: '编号', titleAndPath: '标题 / 相对路径', quality: '清晰度未知', nfo: 'NFO', qualityUnavailable: '清晰度未知', nfoStatusUnavailable: 'NFO 状态未知',
    tmdbSearch: 'TMDb 搜索', tmdbMatch: 'TMDb 匹配', matchCandidates: '候选结果', results: '个结果', closeCandidates: '关闭候选结果', searchingCandidates: '正在从 TMDb 搜索候选结果…', select: '选择', noCandidates: '未找到匹配的候选结果。', nfoSavePreview: 'NFO 保存预览', conflict: '冲突', overwrite: '覆盖', newFile: '新文件', nfoPreview: 'NFO 预览', closeNfoPreview: '关闭 NFO 预览', target: '目标', nfoConflictHelp: '目标不是可替换的普通 NFO 文件。', nfoReplaceHelp: '已有本地 NFO 将以原子方式替换。', xmlContent: 'XML 内容', cancel: '取消', apply: '应用',
    artworkPreview: '图片下载预览', artworkHelp: '仅下载已选择的 TMDb JPEG 图片；确认后才会写入电影所在目录。', poster: '海报', artworkCreate: '将创建新的本地图片文件。', artworkReplace: '将以原子方式替换已有本地图片。', artworkConflict: '目标不是可替换的普通图片文件。', downloadArtwork: '下载图片', downloading: '正在下载…', artworkEyebrow: 'TMDb 图片资源',
    errorSignIn: '无法登录', errorLoadMedia: '无法加载媒体详情', errorSearchCandidates: '搜索候选结果失败', errorApplyCandidate: '应用候选结果失败', errorSaveMetadata: '保存元数据失败', errorPreviewNfo: '预览 NFO 失败', errorWriteNfo: '写入 NFO 失败', errorLoadShow: '无法加载电视剧详情'
  }
} as const

export function useLocale() {
  const initial = localStorage.getItem('mediagrap.locale') === 'zh-CN' ? 'zh-CN' : 'en'
  const locale = shallowRef<Locale>(initial)
  const t = computed(() => messages[locale.value])

  function setLocale(value: Locale) {
    locale.value = value
    localStorage.setItem('mediagrap.locale', value)
  }

  function toggleLocale() {
    setLocale(locale.value === 'en' ? 'zh-CN' : 'en')
  }

  return { locale, t, setLocale, toggleLocale }
}
